[package]
name = "driver-common"
version = "0.1.1"
edition.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true
description = "Platform-agnostic audio driver trait for system-wide audio capture"

[lib]
name = "driver_common"
crate-type = ["lib"]

[dependencies]
serde = { workspace = true }
log = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
