[package]
name = "sotf-daemon"
description = "an audio player and recorder that support audio plugins"
version = "0.1.38"
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = []
hal = ["driver-hal", "sotf-plugins/hal", "sotf-engine/hal"]
asio = ["sotf-engine/asio"]

[[bin]]
name = "sotf-daemon"
path = "bin/sotf_daemon.rs"

[dependencies]
driver-common = { workspace = true }
parking_lot = { workspace = true }
sotf-plugins = { workspace = true }
sotf-engine = { workspace = true }
sotf-player = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ctrlc = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
cpal = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
driver-hal = { workspace = true, optional = true }
objc2-core-audio = { workspace = true, features = ["std", "objc2-core-audio-types", "AudioHardware"], default-features = false }
objc2-core-foundation = { workspace = true, features = ["std", "CFString"], default-features = false }

[dev-dependencies]
serial_test = { workspace = true }
tempfile = { workspace = true }
insta = { workspace = true }
proptest = { workspace = true }
